stages:
  load_data:
    cmd: python src/load_data.py --config=params.yaml
    deps:
    - raw/data_given/heart.csv
    - src/get_data.py
    - src/load_data.py
    outs:
    - raw/heart.csv
  split_data:
    cmd: python src/split_data.py --config=params.yaml
    deps:
    - raw/heart.csv
    - src/split_data.py
    outs:
    - data/processed/test_heart.csv
    - data/processed/train_heart.csv
  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=params.yaml
    deps:
    - data/processed/test_heart.csv
    - data/processed/train_heart.csv
    - src/train_and_evaluate.py
    params:
    - estimators.ElasticNet.params.alpha
    - estimators.ElasticNet.params.l1_ratio
    outs:
    - saved_models/model.joblib
    metrics:
    - reports/params.json:
        cache: false
    - reports/scores.json:
        cache: false
