stages:
  load_data:
    cmd: python src/load_data.py --config= param.yaml
    deps:
      - src/get_data.py
      - src/load_data.py
      - raw/data_given/heart.csv
    outs:
      - raw/heart.csv

  split_data:
    cmd: python src/split_data.py --config=param.yaml
    deps:
      - src/split_data.py
      - raw/heart.csv
    outs:
      - data/processed/train_heart.csv
      - data/processed/test_heart.csv

  train_and_evaluate:
    cmd: python src/train_and_evaluate.py --config=param.yaml
    deps:
      - data/processed/train_heart.csv
      - data/processed/test_heart.csv 
      - src/train_and_evaluate.py
    params:
      - estimators.ElasticNet.params.alpha
      - estimators.ElasticNet.params.l1_ratio
    metrics:
      - report/scores.json:
          cache: false
      - report/params.json:
          cache: false
    outs:
      - saved_models/model.joblib