base:
  project: Coronary Heart Disease Prediction
  random_state: 44
  target_col: target

data_source:
  raw_data: raw/data_given/heart.csv

load_data:
  raw_data: raw/heart.csv

split_data:
  train_path: data/processed/train_heart.csv
  test_path: data/processed/test_heart.csv
  test_size: 0.3
reports:
  scores: reports/scores.json
  params: reports/params.json
estimators:
  ElasticNet:
    params:
      alpha: 0.88
      l1_ratio: 0.89
model_dir: saved_models